# Start Eval

Notes for what to do:


*   Import files (test folds and result json files)
*   Parse through files to get individual groups and their recommendations and a list of tuples
*   Run eval function on results using test matrix
*   Comput for 5 fold and take mean of metrics for that

## Import files and packages

In [15]:
import pandas as pd
import numpy as np
import json
from google.colab import drive
import math
import os
from collections import defaultdict

In [16]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Get recommendation lists with their groups

In [17]:
file_path = '/content/drive/MyDrive/Replication/Replication Outputs/diverse_groups-100_size-8_fold_1_list-size-3_a_j_0.5_greedy_recommendations_20250503_003105.json'

with open(file_path, 'r') as json_file:
    data = json.load(json_file)

for key, value_list in data.items():
    ids = key.split(',')  # split the key into individual string IDs
    ids = [x for x in ids]  # convert to integers
    print(f"Group IDs: {ids} => Recommended Items: {value_list}")

# print(data)

Group IDs: ['1305', '1309', '1318', '1346', '1357', '2911', '4273', '6034'] => Recommended Items: [356, 1219, 32]
Group IDs: ['324', '665', '1548', '1582', '4128', '4151', '4665', '5006'] => Recommended Items: [913, 2706, 50]
Group IDs: ['46', '47', '1305', '3338', '4584', '4602', '4923', '5332'] => Recommended Items: [527, 1193, 110]
Group IDs: ['1488', '1536', '1933', '5834', '5849', '5859', '5891', '5919'] => Recommended Items: [858, 260, 321]
Group IDs: ['2357', '2363', '2373', '2375', '2388', '4110', '4257', '6034'] => Recommended Items: [593, 858, 1248]
Group IDs: ['1123', '1154', '1573', '2037', '2343', '2623', '4955', '5911'] => Recommended Items: [356, 593, 1947]
Group IDs: ['1043', '2356', '2357', '2687', '3577', '5130', '5934', '5999'] => Recommended Items: [527, 1213, 7]
Group IDs: ['16', '704', '1035', '1452', '1477', '2234', '2632', '5967'] => Recommended Items: [913, 1193, 2975]
Group IDs: ['766', '805', '835', '1231', '1810', '2123', '2834', '4413'] => Recommended Items: [1617, 539, 111]
Group IDs: ['1042', '1840', '1927', '2635', '2729', '3938', '4018', '5195'] => Recommended Items: [858, 260, 1965]
Group IDs: ['356', '1615', '1919', '2037', '2133', '2204', '4244', '5161'] => Recommended Items: [593, 2987, 12]
Group IDs: ['12', '21', '852', '906', '3302', '3360', '4749', '5356'] => Recommended Items: [1210, 2918, 111]
Group IDs: ['2707', '2710', '2714', '4315', '4319', '4321', '4325', '4504'] => Recommended Items: [2858, 1, 21]
Group IDs: ['11', '1382', '3937', '3938', '3966', '3968', '6005', '6031'] => Recommended Items: [110, 590, 8]
Group IDs: ['46', '1615', '3570', '3838', '4061', '4974', '4991', '5488'] => Recommended Items: [2858, 366, 908]
Group IDs: ['43', '61', '1237', '3444', '3472', '4805', '6017', '6029'] => Recommended Items: [2762, 21, 253]
Group IDs: ['112', '1169', '2210', '2834', '3828', '3838', '4109', '4597'] => Recommended Items: [541, 111, 235]
Group IDs: ['71', '833', '2104', '2111', '5637', '5918', '5973', '5997'] => Recommended Items: [111, 480, 1196]
Group IDs: ['1777', '1788', '1795', '1814', '1910', '4910', '5258', '5978'] => Recommended Items: [260, 1617, 111]
Group IDs: ['94', '1270', '1813', '2381', '3588', '4348', '5965', '6015'] => Recommended Items: [2858, 1193, 551]
Group IDs: ['67', '74', '79', '82', '4325', '5601', '5907', '5934'] => Recommended Items: [908, 800, 62]
Group IDs: ['21', '356', '812', '1562', '2169', '2708', '4008', '5018'] => Recommended Items: [2676, 2490, 3499]
Group IDs: ['47', '312', '315', '2245', '3739', '4754', '5012', '5934'] => Recommended Items: [527, 1299, 277]
Group IDs: ['1619', '2329', '2346', '3275', '3704', '4102', '4110', '5067'] => Recommended Items: [908, 21, 596]
Group IDs: ['103', '430', '1931', '3326', '3342', '3343', '4836', '5192'] => Recommended Items: [2160, 223, 7]
Group IDs: ['94', '1287', '2525', '3062', '3631', '3634', '4965', '6009'] => Recommended Items: [2028, 1608, 551]
Group IDs: ['14', '2850', '2930', '3015', '3030', '3034', '3039', '3043'] => Recommended Items: [2858, 920, 296]
Group IDs: ['1439', '1477', '2204', '3275', '3893', '3897', '5215', '5706'] => Recommended Items: [1617, 515, 111]
Group IDs: ['12', '1092', '2318', '2816', '2856', '4776', '4778', '4804'] => Recommended Items: [919, 457, 185]
Group IDs: ['46', '1042', '1214', '1539', '1908', '2722', '3455', '3528'] => Recommended Items: [260, 1327, 11]
Group IDs: ['826', '1615', '1838', '2834', '3163', '3838', '4008', '5334'] => Recommended Items: [111, 3083, 1114]
Group IDs: ['98', '100', '101', '580', '584', '1342', '3114', '5932'] => Recommended Items: [527, 2028, 260]
Group IDs: ['1813', '2045', '2441', '3642', '3838', '4628', '5069', '5355'] => Recommended Items: [2858, 1617, 13]
Group IDs: ['473', '511', '1927', '2429', '3537', '4873', '4874', '5529'] => Recommended Items: [110, 858, 3793]
Group IDs: ['3015', '3616', '4517', '4912', '4991', '5069', '5467', '5656'] => Recommended Items: [1179, 2762, 213]
Group IDs: ['50', '71', '2245', '2347', '4025', '4052', '4491', '4492'] => Recommended Items: [2858, 480, 11]
Group IDs: ['51', '60', '747', '1612', '1751', '1756', '1760', '1967'] => Recommended Items: [110, 356, 1]
Group IDs: ['128', '4944', '5895', '5896', '5928', '5929', '5932', '6038'] => Recommended Items: [2858, 32, 50]
Group IDs: ['21', '775', '1918', '2176', '3552', '3893', '3962', '5819'] => Recommended Items: [1212, 1784, 344]
Group IDs: ['21', '46', '572', '2204', '2440', '3179', '5101', '5734'] => Recommended Items: [1210, 2858, 366]
Group IDs: ['745', '1226', '1835', '3043', '3132', '3133', '3959', '4008'] => Recommended Items: [1221, 1193, 3578]
Group IDs: ['51', '1131', '3293', '4654', '4778', '4781', '5513', '5725'] => Recommended Items: [318, 912, 2858]
Group IDs: ['108', '416', '2920', '4424', '4427', '4955', '5101', '6004'] => Recommended Items: [1214, 2762, 1]
Group IDs: ['47', '1589', '3570', '3642', '3911', '3939', '4636', '4776'] => Recommended Items: [36, 356, 260]
Group IDs: ['60', '61', '69', '2396', '2912', '2936', '5958', '5959'] => Recommended Items: [318, 232, 858]
Group IDs: ['738', '741', '742', '1862', '2759', '3060', '3061', '3063'] => Recommended Items: [260, 50, 1968]
Group IDs: ['53', '1927', '2044', '2045', '2111', '2357', '4211', '4628'] => Recommended Items: [920, 593, 13]
Group IDs: ['108', '109', '1336', '2686', '2687', '2695', '5270', '6017'] => Recommended Items: [1, 260, 608]
Group IDs: ['43', '871', '1209', '1751', '2235', '3448', '4441', '4503'] => Recommended Items: [110, 356, 2028]
Group IDs: ['4', '1992', '2512', '2514', '2539', '2687', '2690', '5962'] => Recommended Items: [608, 1198, 356]
Group IDs: ['21', '1808', '1814', '1818', '2345', '2982', '2983', '5310'] => Recommended Items: [910, 2916, 260]
Group IDs: ['94', '852', '1236', '1888', '1892', '2711', '3246', '5088'] => Recommended Items: [912, 1210, 1270]
Group IDs: ['42', '43', '3015', '5529', '5577', '6003', '6004', '6005'] => Recommended Items: [356, 2762, 920]
Group IDs: ['1892', '1893', '2128', '2639', '4314', '4770', '5651', '5652'] => Recommended Items: [593, 912, 780]
Group IDs: ['46', '61', '1886', '2149', '2292', '3583', '4403', '4549'] => Recommended Items: [589, 1644, 7]
Group IDs: ['826', '1309', '1864', '3043', '3838', '3893', '4425', '5174'] => Recommended Items: [356, 3083, 2068]
Group IDs: ['61', '101', '1911', '3530', '3582', '5969', '5970', '5979'] => Recommended Items: [736, 2762, 34]
Group IDs: ['12', '46', '1382', '1385', '1405', '1410', '1412', '2320'] => Recommended Items: [858, 910, 2858]
Group IDs: ['2541', '2586', '2858', '5052', '5168', '5173', '5525', '6017'] => Recommended Items: [356, 1, 2687]
Group IDs: ['67', '1603', '1610', '4486', '4487', '4491', '4495', '5224'] => Recommended Items: [2571, 50, 110]
Group IDs: ['64', '653', '782', '1704', '1754', '4286', '4651', '6027'] => Recommended Items: [110, 296, 2396]
Group IDs: ['47', '51', '60', '61', '1043', '4564', '4567', '4662'] => Recommended Items: [1230, 2324, 3114]
Group IDs: ['1250', '1864', '2965', '2977', '4383', '4385', '4549', '4746'] => Recommended Items: [318, 2858, 3910]
Group IDs: ['1562', '1864', '1919', '2045', '2465', '3843', '4797', '5529'] => Recommended Items: [356, 3948, 1]
Group IDs: ['79', '84', '227', '1963', '4527', '4529', '4530', '5257'] => Recommended Items: [318, 1198, 800]
Group IDs: ['28', '31', '1573', '2049', '2053', '2622', '3350', '3352'] => Recommended Items: [750, 1197, 25]
Group IDs: ['74', '77', '1041', '2616', '2617', '2622', '2623', '4065'] => Recommended Items: [34, 246, 356]
Group IDs: ['1123', '1477', '2159', '3623', '4028', '4955', '5221', '5334'] => Recommended Items: [913, 1617, 199]
Group IDs: ['4', '21', '46', '79', '1661', '4348', '4707', '5611'] => Recommended Items: [1387, 2858, 17]
Group IDs: ['46', '1336', '1341', '1342', '1352', '1359', '2594', '3857'] => Recommended Items: [1, 1213, 1973]
Group IDs: ['46', '242', '3291', '3739', '5101', '5146', '5529', '5802'] => Recommended Items: [3079, 50, 110]
Group IDs: ['61', '1840', '2037', '2829', '3838', '3893', '3969', '5136'] => Recommended Items: [541, 2858, 111]
Group IDs: ['791', '1250', '3570', '4017', '4372', '4394', '4548', '4628'] => Recommended Items: [2858, 2997, 527]
Group IDs: ['79', '512', '2696', '2767', '2834', '3013', '3818', '4110'] => Recommended Items: [800, 898, 904]
Group IDs: ['826', '1893', '1967', '2909', '2977', '4244', '4880', '5146'] => Recommended Items: [527, 1050, 5]
Group IDs: ['29', '30', '600', '1956', '3911', '3939', '5400', '6008'] => Recommended Items: [858, 50, 1]
Group IDs: ['21', '1396', '3542', '3570', '4110', '4270', '4628', '6012'] => Recommended Items: [34, 527, 858]
Group IDs: ['1154', '1228', '1487', '1713', '1783', '1838', '4008', '4288'] => Recommended Items: [356, 1968, 3510]
Group IDs: ['3382', '3396', '4548', '4772', '4774', '4807', '5095', '6038'] => Recommended Items: [1036, 903, 597]
Group IDs: ['46', '2440', '2441', '2819', '3275', '3776', '4486', '5180'] => Recommended Items: [1644, 1, 260]
Group IDs: ['54', '2440', '2441', '2442', '2443', '4145', '4155', '5471'] => Recommended Items: [919, 1270, 2791]
Group IDs: ['30', '2245', '4442', '4444', '6007', '6011', '6012', '6015'] => Recommended Items: [1, 316, 593]
Group IDs: ['111', '1092', '3039', '4196', '4211', '4240', '5918', '6034'] => Recommended Items: [913, 1961, 3578]
Group IDs: ['1226', '2053', '2647', '2710', '3969', '4074', '5185', '5899'] => Recommended Items: [858, 3910, 527]
Group IDs: ['445', '568', '2339', '2582', '3803', '4178', '4537', '5238'] => Recommended Items: [356, 1097, 34]
Group IDs: ['677', '3149', '4254', '4955', '5529', '5694', '5967', '6029'] => Recommended Items: [110, 1282, 2908]
Group IDs: ['304', '1382', '1821', '2204', '3158', '4211', '5529', '5899'] => Recommended Items: [110, 913, 30]
Group IDs: ['432', '1026', '1110', '2588', '3895', '4595', '5116', '5899'] => Recommended Items: [2396, 541, 52]
Group IDs: ['1486', '2574', '2622', '2667', '2704', '4282', '4288', '4293'] => Recommended Items: [858, 2000, 1]
Group IDs: ['21', '1562', '2440', '3838', '4244', '4549', '4802', '4804'] => Recommended Items: [2858, 24, 724]
Group IDs: ['61', '1823', '2039', '2257', '2708', '3537', '5899', '5967'] => Recommended Items: [1784, 2762, 104]
Group IDs: ['2104', '2204', '2343', '2653', '3627', '4270', '4912', '5999'] => Recommended Items: [2959, 296, 541]
Group IDs: ['61', '1037', '2245', '2752', '3149', '3537', '4196', '4896'] => Recommended Items: [3624, 3752, 3618]
Group IDs: ['986', '1840', '2204', '2867', '3112', '3838', '5069', '5101'] => Recommended Items: [1617, 110, 1210]
Group IDs: ['47', '4450', '4453', '4454', '4486', '5247', '5354', '5358'] => Recommended Items: [17, 21, 50]
Group IDs: ['38', '525', '2602', '2982', '3962', '4056', '5275', '5999'] => Recommended Items: [527, 1248, 1]
Group IDs: ['1275', '3496', '3530', '3535', '3552', '3616', '3649', '5152'] => Recommended Items: [1204, 1210, 110]
Group IDs: ['1382', '1821', '2312', '2347', '4299', '4474', '5067', '5383'] => Recommended Items: [260, 1207, 6]
Group IDs: ['61', '1783', '1893', '3144', '4463', '5917', '5967', '6012'] => Recommended Items: [1097, 3317, 50]
Group IDs: ['356', '1295', '1562', '1967', '3739', '3773', '3897', '4270'] => Recommended Items: [1617, 3499, 111]

### Get testing matrix

In [ ]:
test_matrix = pd.read_csv('test_matrix_fold_1.csv', index_col='userId')
test_matrix.head()
test_matrix.loc[5]
int(test_matrix.loc[1305].notna().sum())

3

# Eval function

In [18]:
def evaluate(group, recommendations, test_matrix, k):
  precision_scores = []
  recall_scores = []
  f_scores = []
  ndcg_scores = []


  for user in group:
    print(f'User: {user}')

    if user not in test_matrix.index:
      print(f"User {user} not found in test_matrix.")
      continue
    #need to get true items from user's in the test set
    true_items = set(test_matrix.loc[user].dropna().index)
    print(f'True items: {true_items}')
    #if user has no test data skip user
    if not true_items:
      print(f"User {user} has no test items.")
      continue

    recommended_items = recommendations[:k]
    print(f'recommended_items { recommended_items}')
    hits = [1 if item in true_items else 0 for item in recommended_items]
    print(f'hits: {hits}')

    precision = sum(hits)/k
    recall = sum(hits)/ min(k, len(true_items))
    if precision + recall == 0:
        f1 = 0
    else:
        f1 = 2 * precision * recall / (precision + recall)


    dcg = sum([hit / math.log2(i + 2) for i, hit in enumerate(hits)])
    idcg = sum([1 / math.log2(i + 2) for i in range(min(len(true_items), k))])
    ndcg = dcg / idcg if idcg > 0 else 0

    precision_scores.append(precision)
    recall_scores.append(recall)
    f_scores.append(f1)
    ndcg_scores.append(ndcg)

  return {
      'precision': float(np.mean(precision_scores)),
      'recall': float(np.mean(recall_scores)),
      'f1': float(np.mean(f_scores)),
      'ndcg': float(np.mean(ndcg_scores))
  }

# Start testing

### Single Fold Eval

In [19]:
def evaluate_indiv_fold(group_data, test_matrix, k):
  fold_precesion_scores = []
  fold_recall_scores = []
  fold_f_scores = []
  fold_ndcg_scores = []

  for key, items in group_data.items():
    group = [int(x) for x in key.split(',')]
    recs = [str(x) for x in items]
    metrics = evaluate(group, recs, test_matrix, k)

    fold_precesion_scores.append(metrics['precision'])
    fold_recall_scores.append(metrics['recall'])
    fold_f_scores.append(metrics['f1'])
    fold_ndcg_scores.append(metrics['ndcg'])

  return {
      'precision': float(np.mean(fold_precesion_scores)),
      'recall': float(np.mean(fold_recall_scores)),
      'f1': float(np.mean(fold_f_scores)),
      'ndcg': float(np.mean(fold_ndcg_scores))
  }

# Build function for a complete eval

## separate files and build groups with them

Notes for indices of file names


*   0: group type
*   4: fold #
*   5: list size (which needs to be split)
*   7: type
*   8: lamda

In [24]:
output_folder = '/content/drive/MyDrive/Replication/Replication Outputs'
all_files = os.listdir(output_folder)

grouped_files = defaultdict(lambda: {})

for filename in all_files:
  # print(filename)
  parts = filename.split('_')
  print(parts)
  if len(parts) < 13:
      continue

  group_type = parts[0]  # 'diverse'
  list_size = parts[5]   # 'list-size-3'
  utility = parts[6]     # 'a'
  fairness = parts[7]    # 'var'
  fold_number = parts[4] # '1'
  lambda_val = parts[8]

  key = (group_type, list_size, utility, fairness, lambda_val)
  grouped_files[key][fold_number] = filename


final_groups = []

for key, fold_dict in grouped_files.items():
  if all(str(fold) in fold_dict for fold in range(1, 6)):
        group_of_files = [fold_dict[str(fold)] for fold in range(1, 6)]
        final_groups.append(group_of_files)

print(f"Found {len(final_groups)} complete 5-fold groups.")

for fname in final_groups:
    print(fname)

['No Cross Validation']

IndexError: list index out of range

In [26]:
import re
from collections import defaultdict
import os

output_folder = '/content/drive/MyDrive/Replication/Replication Outputs'
all_files = os.listdir(output_folder)

# Example regex pattern
pattern = re.compile(
    r'^(?P<group_type>\w+)_groups-100_size-8_fold_(?P<fold>\d+)_list-size-(?P<list_size>\d+)_'
    r'(?P<utility>[a-z])_(?P<fairness>[a-z]+)_(?P<lambda>\d+(?:\.\d+)?)_greedy_recommendations'
)


grouped_files = defaultdict(dict)

for filename in all_files:
    match = pattern.match(filename)
    if not match:
        print(f"Skipping: {filename}")  # Debug if needed
        continue

    gd = match.groupdict()
    key = (gd['group_type'], gd['list_size'], gd['utility'], gd['fairness'], gd['lambda'])
    grouped_files[key][gd['fold']] = filename

# Collect final groups with all 5 folds
final_groups = []

for key, fold_dict in grouped_files.items():
    if all(str(fold) in fold_dict for fold in range(1, 6)):
        group_of_files = [fold_dict[str(fold)] for fold in range(1, 6)]
        final_groups.append(group_of_files)

print(f"Found {len(final_groups)} complete 5-fold groups.")

Skipping: No Cross Validation
Found 130 complete 5-fold groups.

In [7]:
# get test files
test_folder = '/content/drive/MyDrive/Replication/Test Files'
test_filenames = sorted(os.listdir(test_folder))
# print(test_filenames)

test_matrices = []

for filename in test_filenames:
    file_path = os.path.join(test_folder, filename)
    test_matrix = pd.read_csv(file_path, index_col='userId')
    test_matrices.append(test_matrix)

5.0

## Main Driver (Binary)

In [27]:
results_by_config = {}

for group in final_groups:
  fold_metrics = []

  # need to find k group was evaluated using
  file = group[0]
  parts = file.split('_')
  val = parts[5]
  k = int(val.split('-')[2])
  # print(k)x
  for fold_idx, filename in enumerate(group):
    # need to find k val

    file_path = os.path.join(output_folder, filename)
    with open(file_path, 'r') as json_file:
        group_data = json.load(json_file)

    test_matrix = test_matrices[fold_idx]
    metrics = evaluate_indiv_fold(group_data, test_matrix, k)
    fold_metrics.append(metrics)


    avg_metrics = {
    'precision': float(np.mean([m['precision'] for m in fold_metrics])),
    'recall': float(np.mean([m['recall'] for m in fold_metrics])),
    'f1': float(np.mean([m['f1'] for m in fold_metrics])),
    'ndcg': float(np.mean([m['ndcg'] for m in fold_metrics]))
    }

    parts = group[0].split('_')
    group_type = parts[0]
    list_size = parts[5]            # e.g., 'list-size-3'
    utility = parts[6]              # e.g., 'a'
    fairness = parts[7]            # e.g., 'var'
    lambda_val = parts[8]          # e.g., '0.5'

    config_key = (group_type, list_size, utility, fairness, lambda_val)
    results_by_config[config_key] = avg_metrics

Streaming output truncated to the last 5000 lines.
User: 4169
True items: {'3061', '2951', '2269', '3914', '3641', '1044', '650', '3055', '3006', '1198', '1398', '3261', '2479', '1245', '2070', '1413', '1684', '3678', '2989', '52', '3339', '3197', '3870', '2848', '1632', '2029', '3173', '948', '1408', '1214', '2102', '3029', '2699', '2969', '1969', '2952', '3468', '1954', '2783', '913', '1732', '2916', '2575', '3160', '3258', '3619', '360', '457', '2154', '2161', '135', '2885', '1955', '2906', '3682', '1885', '3319', '3770', '149', '2944', '3728', '2527', '1381', '3072', '612', '1391', '2867', '885', '2621', '848', '460', '1256', '3152', '1917', '3593', '2117', '2535', '1355', '2467', '3668', '1672', '3725', '1590', '2246', '261', '968', '2565', '3884', '2341', '1962', '932', '3826', '852', '2903', '2476', '1208', '1243', '270', '2434', '435', '2444', '2633', '271', '2526', '3910', '275', '2792', '3267', '1121', '3292', '2126', '3255', '3896', '2006', '256', '3451', '2430', '3935', '41', '3459', '2212', '2047', '2949', '2812', '914', '2376', '1008', '2670', '3105', '257', '1396', '1501', '574', '173', '2561', '919', '1285', '3212', '2010', '3100', '26', '1841', '2522', '898', '2905', '897', '2948', '1343', '1252', '247', '1353', '2532', '2144', '2409', '3675', '1071', '1483', '1026', '966', '2441', '3', '1752', '3372', '3893', '308', '1959', '943', '3316', '3117', '1442', '3556', '2764', '1272', '1927', '195', '2967', '3158', '442', '2482', '242', '2013', '236', '3102', '1284', '2436', '595', '1378', '3405', '3657', '2784', '829', '3590', '1029', '3371', '424', '1317', '1680', '1130', '2384', '915', '1918', '2587', '125', '659', '1625', '530', '2184', '3506', '289', '1678', '513', '1535', '3218', '933', '2901', '1835', '3163', '994', '1479', '3030', '2334', '410', '2541', '114', '2236', '503', '2429', '3456', '937', '3926', '673', '1177', '86', '1921', '1934', '209', '3720', '1428', '2352', '1957', '2007', '806', '2796', '3169', '1003', '3927', '1010', '3683', '2405', '2647', '2789', '2912', '1352', '3331', '506', '2486', '3763', '2882', '1119', '2300', '2570', '20', '725', '3638', '736', '800', '1066', '3507', '43', '1412', '1610', '2517', '3501', '2577', '334', '2990', '2539', '93', '32', '2450', '1061', '1332', '1028', '2066', '838', '45', '1943', '1394', '2856', '951', '660', '3655', '137', '2612', '237', '2187', '2359', '540', '788', '307', '1611', '1853', '1464', '1513', '2301', '2335', '2146', '3284', '352', '1407', '3710', '1799', '5', '3427', '489', '3925', '231', '111', '514', '3559', '444', '2076', '1079', '2019', '1288', '2536', '749', '893', '588', '3742', '471', '2663', '2890', '1792', '597', '3147', '1938', '3515', '28', '3044', '2311', '1916', '280', '1584', '2580', '3435', '2542', '3349', '2248', '3685', '2159', '2519', '1900', '3816', '2646', '750', '2554', '2426', '3217', '2096', '417', '3150', '3048', '2124', '3503', '2316', '3653', '1416', '3702', '34', '2336', '3857', '293', '3153', '833', '3359', '555', '177', '2662', '218', '1357', '2660', '383', '3897', '3219', '997', '3235', '2712', '2375', '1627', '282', '2858', '202', '1025', '2805', '2143', '1228', '615', '46', '80', '547', '3446', '1273', '1264', '2193', '2585', '775', '94', '3555', '3207', '2353', '1341', '102', '2571', '2084', '1948', '2598', '967', '3161', '2728', '497', '2982', '931', '2397', '2817', '965', '1302', '3132', '1696', '2350', '1939', '1260', '222', '2363', '2174', '2501', '168', '3703', '2650', '917', '3208', '31', '694', '1674', '3476', '351', '748', '2863', '908', '3135', '1230', '196', '415', '1642', '3532', '1379', '1964', '85', '2639', '3329', '3614', '925', '2611'}
recommended_items ['260', '296', '527', '480', '2571', '3362', '2762', '592', '1953', '780']
hits: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
User: 4474
True items: {'858', '2194', '1221', '2616', '762', '1968', '1466', '1227', '2469'}
recommended_items ['260', '296', '527', '480', '2571', '3362', '2762', '592', '1953', '780']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 2231
True items: {'1104', '2852', '1233', '3789', '1957', '2159', '368', '1466', '2926', '1963', '1226', '2361', '3445', '3028', '1639', '1240', '3675', '2202', '2181', '265', '1246', '2110', '920', '2969', '3104', '1937', '1295', '1234', '1307', '1954', '1959', '3394', '3507', '2857', '3430', '2899', '3733', '2732', '3404', '3107', '3684', '2285', '1344', '1627', '1225', '1179', '2858', '922', '1580', '1267', '1189', '1394', '3067', '3037', '356', '3555', '3590', '3152', '1193', '3090', '1948', '2133', '2692', '592', '2407', '1617', '3343', '3196', '1760', '1082', '965', '3427', '1203', '661', '3210', '1380', '1213', '2870', '3529', '933', '1674', '3168', '2006', '3451', '3099', '1950', '2081', '3075', '1294', '3929', '1224', '1964', '2000', '3926', '1097', '902', '1276'}
recommended_items ['2028', '858', '3578', '260', '2762', '111', '1721', '1196', '480', '3755']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 2326
True items: {'1030', '3510', '3916', '1356', '688', '1339', '2628', '3668', '2762', '3708', '260', '2888', '1376', '2122', '1126', '1059', '1302', '3481', '3699'}
recommended_items ['2028', '858', '3578', '260', '2762', '111', '1721', '1196', '480', '3755']
hits: [0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
User: 3577
True items: {'17', '1569', '2875', '1408', '3257', '1441', '2491', '1605', '222', '361', '1947', '1043', '3', '1888'}
recommended_items ['2028', '858', '3578', '260', '2762', '111', '1721', '1196', '480', '3755']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 3861
True items: {'2329', '110', '1089', '3752', '1466', '2485', '593', '3182', '318'}
recommended_items ['2028', '858', '3578', '260', '2762', '111', '1721', '1196', '480', '3755']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 398
True items: {'1079', '3452', '2724', '541', '2278', '1500', '1175', '3081', '3274', '3386', '2289', '1953', '1917', '2353', '3160', '3396', '1215', '3298', '21', '3168', '2628', '1171', '1488', '1060', '1479', '2599', '2116', '2734', '1089', '441', '185', '2763', '1769', '2858', '648', '3794', '32', '2028', '2804', '2707', '1625', '2706', '3361', '1240', '2844', '1580', '1608', '1078'}
recommended_items ['2028', '858', '3578', '260', '2762', '111', '1721', '1196', '480', '3755']
hits: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 5487
True items: {'2393', '2011', '3325', '589', '1210', '2959', '1721', '260', '2474', '1198', '3354', '3623'}
recommended_items ['2028', '858', '3578', '260', '2762', '111', '1721', '1196', '480', '3755']
hits: [0, 0, 0, 1, 0, 0, 1, 0, 0, 0]
User: 775
True items: {'3646', '2858', '344', '3535', '3753'}
recommended_items ['2028', '858', '3578', '260', '2762', '111', '1721', '1196', '480', '3755']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 81
True items: {'3435', '2879', '1193', '1348', '908', '1214', '1299', '3362', '3468', '3683', '2924', '978', '1263', '1213', '905', '1198', '2971', '1617'}
recommended_items ['2028', '858', '3578', '260', '2762', '111', '1721', '1196', '480', '3755']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 1553
True items: {'923', '1136', '1468', '2080', '1097', '2699', '1380', '920', '1197', '2396', '34'}
recommended_items ['110', '3114', '1580', '2716', '2916', '1136', '1073', '1221', '1097', '2762']
hits: [0, 0, 0, 0, 0, 1, 0, 0, 1, 0]
User: 2021
True items: {'2898', '1408', '891', '1214', '2004', '2782', '1858', '1994', '1258', '724', '2428', '555', '507', '1047', '3081', '3274', '3256', '1527', '1488', '3661', '1667', '480', '1676', '3107', '1573', '2976', '2003', '3082', '3499', '1690', '1407', '2167', '3535', '95', '1762'}
recommended_items ['110', '3114', '1580', '2716', '2916', '1136', '1073', '1221', '1097', '2762']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 245
True items: {'12', '3868', '1248', '1210', '1544', '1320', '3424', '1221', '3362', '2478', '2902', '473', '1409', '2456', '1198', '273', '2553', '3840', '1359', '1474', '3927', '2414', '923', '1125', '2372', '2405', '1947', '2529', '2649', '2402', '1334', '3707', '2948', '1252', '553', '2120', '95', '2851', '3812', '3448', '3471', '3599', '1257', '3070', '3871', '3889', '2110', '1049', '1952', '2040', '2431', '1031', '2194', '3386', '1329', '653', '3525', '1275', '1222', '943', '3507', '3791', '913', '1732', '2517', '2916', '1801', '3706', '1357', '122', '2054', '2764', '480', '1272', '457', '2985', '996', '2375', '608', '2717', '2367', '922', '2013', '2475', '2993', '3479', '3682', '2988', '3098', '2474', '2700', '3834', '1219', '3526', '671', '2527', '426', '1298', '3590', '407', '3365', '3401', '2373', '788', '3340', '11', '235', '2657', '1617', '3628', '3444', '2046', '2420', '2476', '1562', '21', '1094', '1250', '1909', '1128', '2791', '2355', '1288', '1263', '1213', '952', '1876', '2174', '168', '588', '2065', '2097', '1953', '2808', '3255', '3476', '2150', '2', '3873', '1372', '3451', '908', '1230', '2567', '1748', '504', '1376', '3487', '300', '3499', '648', '2028', '3418', '2186', '3926', '673', '466', '1276'}
recommended_items ['110', '3114', '1580', '2716', '2916', '1136', '1073', '1221', '1097', '2762']
hits: [0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
User: 2555
True items: {'858', '3801', '1711', '541', '1729', '2987', '2174', '3469', '3363', '1954', '3421', '1092', '1206', '1321', '3196', '3551', '1252', '1267', '3671'}
recommended_items ['110', '3114', '1580', '2716', '2916', '1136', '1073', '1221', '1097', '2762']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 3039
True items: {'3061', '946', '2206', '1212', '906', '1069', '929', '2936', '2205', '913', '1936', '1940', '1935', '953', '3644'}
recommended_items ['110', '3114', '1580', '2716', '2916', '1136', '1073', '1221', '1097', '2762']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 3544
True items: {'2455', '1968', '1699', '1721', '2762', '1224'}
recommended_items ['110', '3114', '1580', '2716', '2916', '1136', '1073', '1221', '1097', '2762']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
User: 4032
True items: {'2872', '1304', '353', '1233', '3527', '3639', '1221', '3638', '1270', '2478', '434', '1382', '1527', '2916', '3681', '2571', '480', '2133', '2366', '2985', '2968', '2640', '3444', '998', '1073', '3197', '1276'}
recommended_items ['110', '3114', '1580', '2716', '2916', '1136', '1073', '1221', '1097', '2762']
hits: [0, 0, 0, 0, 1, 0, 1, 1, 0, 0]
User: 753
True items: {'586', '2294', '1777', '2953', '3785', '2455', '733', '2302', '1911', '1806', '2107', '2109', '2174', '2012', '20', '3565', '3646', '736', '1021', '870', '1474', '2169', '3863', '2335', '2003', '1367', '170', '2657', '2053', '3499', '2059', '3917', '367', '1240', '1562'}
recommended_items ['110', '3114', '1580', '2716', '2916', '1136', '1073', '1221', '1097', '2762']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 1185
True items: {'2792', '3525', '2141', '2072', '3363', '2858', '2015', '408', '3105', '1097', '2699', '1917'}
recommended_items ['1270', '2997', '1220', '2791', '1196', '2858', '1358', '1036', '1197', '2291']
hits: [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
User: 1296
True items: {'3893', '1061', '3129', '3100', '539', '2706', '337'}
recommended_items ['1270', '2997', '1220', '2791', '1196', '2858', '1358', '1036', '1197', '2291']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 1360
True items: {'1374', '3334', '912', '2716', '110', '919', '36', '736', '2628', '1704', '2709', '2987', '592', '2363', '2394', '1250'}
recommended_items ['1270', '2997', '1220', '2791', '1196', '2858', '1358', '1036', '1197', '2291']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 1496
True items: {'858', '3033', '1291', '2302', '2088', '3576', '743', '3694', '1517', '2613', '861', '3809', '3013', '1101', '2525', '919', '1350', '2456', '1198', '1215', '3266', '2797', '3040', '934', '1334', '3693', '1968', '2120', '3688', '1977', '413', '2403', '253', '1241', '3070', '3869', '1214', '1882', '288', '2987', '1482', '1969', '1641', '653', '1275', '1954', '1270', '3258', '2517', '3396', '188', '2378', '1995', '3754', '1980', '2140', '2985', '316', '29', '2858', '329', '1614', '784', '1219', '595', '2641', '1500', '63', '407', '836', '2454', '330', '3401', '102', '1681', '1655', '153', '2116', '1590', '1997', '1405', '160', '70', '429', '2982', '2790', '3535', '2722', '3697', '3018', '3175', '231', '2288', '21', '1128', '1909', '3552', '1485', '1175', '1282', '157', '2174', '1591', '2325', '837', '2642', '3208', '2150', '2121', '1274', '1372', '1479', '181', '745', '1722', '2366', '1278', '2119', '2342', '673', '1584', '2108', '2716', '3757', '1078'}
recommended_items ['1270', '2997', '1220', '2791', '1196', '2858', '1358', '1036', '1197', '2291']
hits: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0]
User: 1830
True items: {'3698', '1370', '2640', '1552', '3863', '1240', '1036', '1196', '377'}
recommended_items ['1270', '2997', '1220', '2791', '1196', '2858', '1358', '1036', '1197', '2291']
hits: [0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
User: 3463
True items: {'2745', '3868', '2804', '1288', '2000', '1028', '2746'}
recommended_items ['1270', '2997', '1220', '2791', '1196', '2858', '1358', '1036', '1197', '2291']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 4260
True items: {'2791', '253', '161', '12', '1597', '1100', '2279', '2651', '2668', '2724', '1468', '2815', '3785', '2793', '1994', '39', '1210', '3837', '3016', '423', '2327', '1347', '2291', '1287', '3646', '1556', '799', '610', '688', '2901', '2664', '550', '736', '3745', '2160', '1350', '3476', '3766', '1215', '512', '2121', '516', '2427', '3662', '2648', '3360', '3799', '1997', '382', '2513', '1721', '2468', '2789', '1242', '2966', '70', '1130', '2315', '440', '3676', '2080', '2817', '1639', '3926', '3826', '3361', '2787', '3175', '3448', '3751', '3572'}
recommended_items ['1270', '2997', '1220', '2791', '1196', '2858', '1358', '1036', '1197', '2291']
hits: [0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
User: 4436
True items: {'2076', '2875', '2840', '3526', '2025', '2702', '2300', '2959', '58', '3753', '2442', '2333', '1923', '1641', '1307', '1270', '2836', '1959', '2718', '1732', '720', '2890', '2795', '2863', '3219', '2734', '1399', '1405', '1663', '1', '934', '2763', '223', '3051', '2574', '2688', '778', '648', '125', '2908', '233', '1639', '2686', '2720', '1011', '1292'}
recommended_items ['1270', '2997', '1220', '2791', '1196', '2858', '1358', '1036', '1197', '2291']
hits: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 1470
True items: {'1306', '1934', '1701', '3793', '2743', '554', '651', '1077', '907', '2608', '939', '2456', '273', '3810', '3096', '2671', '234', '850', '3503', '274', '593', '1196', '897', '1558', '2268', '3181', '3653', '2130', '2948', '1476', '1510', '52', '2147', '1998', '3763', '1866', '2383', '3889', '288', '15', '492', '920', '2864', '2441', '724', '1969', '1218', '99', '3507', '3250', '2916', '3546', '3316', '122', '3897', '446', '3556', '3661', '1570', '1756', '457', '859', '1227', '2572', '1772', '392', '3428', '2947', '3624', '1192', '2406', '566', '3885', '3913', '236', '3865', '312', '895', '1228', '1394', '129', '3594', '3012', '2821', '2128', '3943', '3902', '1386', '3380', '1423', '1626', '3936', '2589', '788', '1365', '3719', '3891', '2687', '691', '3668', '2084', '1493', '3820', '810', '1502', '518', '2055', '3883', '2982', '696', '3444', '1302', '294', '1503', '2742', '3669', '475', '2173', '1805', '3189', '227', '2538', '3916', '3790', '1356', '2708', '1022', '2590', '2233', '908', '847', '1508', '1230', '2541', '3718', '1721', '568', '260', '3407', '522', '2212', '3623', '1115', '1718', '277', '2322', '3551', '977', '98', '280', '2580'}
recommended_items ['457', '2571', '1270', '1527', '1210', '480', '593', '589', '608', '50']
hits: [1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
User: 1872
True items: {'1358', '1921', '110', '2011', '1748', '910', '1016', '1269', '2396', '3476', '593', '573'}
recommended_items ['457', '2571', '1270', '1527', '1210', '480', '593', '589', '608', '50']
hits: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
User: 2458
True items: {'293', '1304', '353', '1220', '3072', '3087', '2174', '2792', '24', '356', '832', '1917', '1610', '1091', '2150', '3501', '2750', '1136', '1676', '230', '196', '474', '2762', '1', '23', '379', '2722', '454', '1028'}
recommended_items ['457', '2571', '1270', '1527', '1210', '480', '593', '589', '608', '50']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 3112
True items: {'1219', '1394', '2015', '2398', '164', '1260', '1197', '1356', '1967', '1259', '1023', '2677', '1610', '2422', '3476', '1029', '1296', '1010', '2628', '2571', '2141', '2826', '2692', '364', '2762', '2529', '2572', '1032', '213', '50', '2694', '3039', '3034', '3461', '594'}
recommended_items ['457', '2571', '1270', '1527', '1210', '480', '593', '589', '608', '50']
hits: [0, 1, 0, 0, 0, 0, 0, 0, 0, 1]
User: 3786
True items: {'2599', '1270', '2712', '1277', '1500', '535', '1673', '2819', '3083', '902', '1357', '1617'}
recommended_items ['457', '2571', '1270', '1527', '1210', '480', '593', '589', '608', '50']
hits: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
User: 5298
True items: {'3703', '1214', '780', '3615', '1676', '2641', '509', '1240', '1584', '1544', '260', '2161', '2916', '316', '3156'}
recommended_items ['457', '2571', '1270', '1527', '1210', '480', '593', '589', '608', '50']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 5332
True items: {'1047', '2365', '1370', '2393', '780', '3624', '1291', '110', '1101', '2273', '1049', '2881', '2880', '457', '1210', '1196'}
recommended_items ['457', '2571', '1270', '1527', '1210', '480', '593', '589', '608', '50']
hits: [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]
User: 5504
True items: {'2115', '2412', '2951', '2668', '1921', '3033', '2815', '2011', '1167', '2010', '2490', '3489', '1036', '1894', '3114', '2427', '1387', '2986', '2402', '1334', '1032', '3578', '2747', '1566', '2409', '3197', '586', '3062', '1408', '1214', '1588', '3264', '2040', '2699', '3438', '1234', '3638', '1270', '2662', '2916', '3396', '516', '3342', '1460', '457', '2375', '316', '135', '2001', '1920', '3384', '1179', '3060', '2408', '1025', '329', '10', '2991', '2918', '2043', '1597', '3545', '1262', '1587', '1080', '3035', '356', '1256', '1373', '3401', '1029', '2083', '158', '2762', '2407', '1018', '710', '3088', '314', '3366', '332', '3427', '1208', '21', '594', '661', '1833', '921', '1085', '2015', '3506', '3591', '1960', '1012', '2559', '2174', '590', '3529', '588', '1586', '2097', '3703', '3742', '471', '610', '1129', '2126', '551', '3247', '924', '2628', '748', '1479', '1136', '1722', '2366', '2949', '1004', '648', '3418', '2134', '1584', '2376', '1078'}
recommended_items ['457', '2571', '1270', '1527', '1210', '480', '593', '589', '608', '50']
hits: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
User: 1462
True items: {'3', '3289', '3484', '1673', '3948', '3354', '594'}
recommended_items ['110', '2858', '1196', '1197', '1580', '3039', '1097', '260', '1210', '2716']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 1815
True items: {'780', '3624', '110', '546', '1580', '260', '765', '2053'}
recommended_items ['110', '2858', '1196', '1197', '1580', '3039', '1097', '260', '1210', '2716']
hits: [1, 0, 0, 0, 1, 0, 0, 1, 0, 0]
User: 3451
True items: {'1641', '2324', '1824', '1485', '2391', '2313', '39', '457', '1732', '1517', '2108'}
recommended_items ['110', '2858', '1196', '1197', '1580', '3039', '1097', '260', '1210', '2716']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 3465
True items: {'741', '2140', '3489', '1', '1196', '608'}
recommended_items ['110', '2858', '1196', '1197', '1580', '3039', '1097', '260', '1210', '2716']
hits: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
User: 4163
True items: {'2013', '2521', '2987', '2147', '1198', '3375', '2628'}
recommended_items ['110', '2858', '1196', '1197', '1580', '3039', '1097', '260', '1210', '2716']
hits: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
User: 4279

In [28]:
print(results_by_config)

{('diverse', 'list-size-3', 'a', 'lm', '0.5'): {'precision': 0.08569877344877344, 'recall': 0.08628676217961932, 'f1': 0.0859339689411118, 'ndcg': 0.0881781443069475}, ('random', 'list-size-3', 'a', 'lm', '0.5'): {'precision': 0.10903571428571428, 'recall': 0.10907738095238093, 'f1': 0.10905238095238094, 'ndcg': 0.11074527658766123}, ('diverse', 'list-size-3', 'a', 'j', '0.5'): {'precision': 0.0765981584553013, 'recall': 0.07714404246547103, 'f1': 0.07681651205936921, 'ndcg': 0.08172937647572365}, ('similar', 'list-size-3', 'a', 'lm', '0.5'): {'precision': 0.12195681302824161, 'recall': 0.122251443001443, 'f1': 0.12207466501752215, 'ndcg': 0.12227325259049551}, ('random', 'list-size-3', 'a', 'j', '0.5'): {'precision': 0.10839285714285714, 'recall': 0.10843452380952381, 'f1': 0.1084095238095238, 'ndcg': 0.11047960024901445}, ('diverse', 'list-size-3', 'a', 'lm', '0.7'): {'precision': 0.08586459836459834, 'recall': 0.08645258709544423, 'f1': 0.0860997938569367, 'ndcg': 0.08829487146480922}, ('random', 'list-size-3', 'a', 'lm', '0.7'): {'precision': 0.1093690476190476, 'recall': 0.10941071428571428, 'f1': 0.10938571428571427, 'ndcg': 0.11097991595067262}, ('similar', 'list-size-3', 'a', 'j', '0.5'): {'precision': 0.12397790833505118, 'recall': 0.12423045076616504, 'f1': 0.12407892530749673, 'ndcg': 0.12372478578483562}, ('similar', 'list-size-3', 'a', 'lm', '0.7'): {'precision': 0.12212602212602212, 'recall': 0.12242065209922352, 'f1': 0.12224387411530269, 'ndcg': 0.12237684614031437}, ('diverse', 'list-size-3', 'a', 'j', '0.7'): {'precision': 0.08535298563869992, 'recall': 0.08589844877344877, 'f1': 0.08557117089259947, 'ndcg': 0.08804658118586814}, ('diverse', 'list-size-3', 'a', 'lm', '0.9'): {'precision': 0.08561545729402872, 'recall': 0.08620344602487459, 'f1': 0.08585065278636707, 'ndcg': 0.08811949655851391}, ('random', 'list-size-3', 'p', 'var', '0.5'): {'precision': 0.06513095238095237, 'recall': 0.06517261904761903, 'f1': 0.06514761904761904, 'ndcg': 0.06723179462572709}, ('random', 'list-size-3', 'p', 'm', '0.5'): {'precision': 0.08614285714285713, 'recall': 0.08618452380952381, 'f1': 0.08615952380952381, 'ndcg': 0.08368766598530444}, ('random', 'list-size-3', 'a', 'lm', '0.9'): {'precision': 0.11103571428571427, 'recall': 0.11107738095238093, 'f1': 0.11105238095238093, 'ndcg': 0.1123067191356157}, ('similar', 'list-size-3', 'p', 'var', '0.5'): {'precision': 0.08565812890812889, 'recall': 0.08595148766577336, 'f1': 0.08575047241118668, 'ndcg': 0.08823309947413777}, ('random', 'list-size-3', 'a', 'j', '0.7'): {'precision': 0.1154047619047619, 'recall': 0.11548809523809525, 'f1': 0.11543809523809523, 'ndcg': 0.11598856771614965}, ('similar', 'list-size-3', 'p', 'm', '0.5'): {'precision': 0.11050331546760117, 'recall': 0.11079582388510958, 'f1': 0.11059531883460454, 'ndcg': 0.10844286942054401}, ('diverse', 'list-size-3', 'p', 'var', '0.7'): {'precision': 0.05726226551226551, 'recall': 0.05756162818662819, 'f1': 0.057382010582010576, 'ndcg': 0.05472212198834124}, ('similar', 'list-size-3', 'a', 'j', '0.7'): {'precision': 0.12178500996358141, 'recall': 0.12203755239469527, 'f1': 0.12188602693602694, 'ndcg': 0.12219699423107004}, ('similar', 'list-size-3', 'a', 'lm', '0.9'): {'precision': 0.12069494262351406, 'recall': 0.1209474850546279, 'f1': 0.12079595959595961, 'ndcg': 0.12135240428685132}, ('diverse', 'list-size-3', 'p', 'lm', '0.5'): {'precision': 0.06562102315673744, 'recall': 0.0660475073867931, 'f1': 0.0657916168487597, 'ndcg': 0.061235589923007275}, ('random', 'list-size-3', 'p', 'lm', '0.5'): {'precision': 0.08614285714285713, 'recall': 0.08618452380952381, 'f1': 0.08615952380952381, 'ndcg': 0.08368766598530444}, ('similar', 'list-size-3', 'p', 'lm', '0.5'): {'precision': 0.11058750773036485, 'recall': 0.11088001614787328, 'f1': 0.11067951109736822, 'ndcg': 0.1085176496721981}, ('diverse', 'list-size-3', 'p', 'lm', '0.7'): {'precision': 0.06562102315673744, 'recall': 0.0660475073867931, 'f1': 0.0657916168487597, 'ndcg': 0.061235589923007275}, ('random', 'list-size-3', 'p', 'lm', '0.7'): {'precision': 0.0860595238095238, 'recall': 0.08610119047619047, 'f1': 0.08607619047619047, 'ndcg': 0.0836290061445516}, ('similar', 'list-size-3', 'p', 'lm', '0.7'): {'precision': 0.11058749055177626, 'recall': 0.11087999896928466, 'f1': 0.11067949391877963, 'ndcg': 0.10857970075963083}, ('diverse', 'list-size-3', 'p', 'lm', '0.9'): {'precision': 0.06562102315673744, 'recall': 0.0660475073867931, 'f1': 0.0657916168487597, 'ndcg': 0.061235589923007275}, ('random', 'list-size-3', 'p', 'lm', '0.9'): {'precision': 0.08614285714285713, 'recall': 0.08618452380952381, 'f1': 0.08615952380952381, 'ndcg': 0.08368766598530444}, ('similar', 'list-size-3', 'p', 'lm', '0.9'): {'precision': 0.11050331546760117, 'recall': 0.1107958238851096, 'f1': 0.11059531883460456, 'ndcg': 0.10848941680535802}, ('diverse', 'list-size-5', 'a', 'lm', '0.5'): {'precision': 0.07919214594928882, 'recall': 0.08372954803133376, 'f1': 0.08078010236802755, 'ndcg': 0.08543816912644889}, ('random', 'list-size-5', 'a', 'lm', '0.5'): {'precision': 0.10725714285714287, 'recall': 0.10848630952380953, 'f1': 0.10772142857142859, 'ndcg': 0.10974057657340792}, ('similar', 'list-size-5', 'a', 'lm', '0.5'): {'precision': 0.12207527313955886, 'recall': 0.12426884491170206, 'f1': 0.12282743760082197, 'ndcg': 0.12331240134861254}, ('random', 'list-size-3', 'a', 'var', '0.5'): {'precision': 0.1161547619047619, 'recall': 0.11619642857142858, 'f1': 0.11617142857142859, 'ndcg': 0.11632955571770758}, ('diverse', 'list-size-3', 'a', 'var', '0.5'): {'precision': 0.07926980691266405, 'recall': 0.08006738301381158, 'f1': 0.07956358482787053, 'ndcg': 0.08140449106084553}, ('diverse', 'list-size-3', 'p', 'var', '0.5'): {'precision': 0.04095162509448223, 'recall': 0.04141376348519206, 'f1': 0.041136480450766164, 'ndcg': 0.042137378013362765}, ('similar', 'list-size-3', 'a', 'var', '0.9'): {'precision': 0.12136837765409195, 'recall': 0.12162092008520582, 'f1': 0.1214693946265375, 'ndcg': 0.12187268762206835}, ('random', 'list-size-3', 'a', 'var', '0.9'): {'precision': 0.11490476190476188, 'recall': 0.11490476190476188, 'f1': 0.11490476190476188, 'ndcg': 0.11527335901246152}, ('diverse', 'list-size-3', 'a', 'var', '0.9'): {'precision': 0.087961605854463, 'recall': 0.08859125266268122, 'f1': 0.08821346457775028, 'ndcg': 0.09010551496844973}, ('similar', 'list-size-3', 'a', 'var', '0.7'): {'precision': 0.12128080120937264, 'recall': 0.12153334364048649, 'f1': 0.12138181818181819, 'ndcg': 0.12181104097845714}, ('random', 'list-size-3', 'a', 'var', '0.7'): {'precision': 0.11373809523809524, 'recall': 0.11373809523809524, 'f1': 0.11373809523809524, 'ndcg': 0.11448284251589895}, ('diverse', 'list-size-3', 'a', 'var', '0.7'): {'precision': 0.08804578093863809, 'recall': 0.0886754277468563, 'f1': 0.08829763966192536, 'ndcg': 0.09014925153790854}, ('similar', 'list-size-3', 'a', 'var', '0.5'): {'precision': 0.1226310382738954, 'recall': 0.12288358070500927, 'f1': 0.12273205524634094, 'ndcg': 0.12284352583099396}, ('diverse', 'list-size-3', 'a', 'm', '0.7'): {'precision': 0.08586459836459834, 'recall': 0.08645258709544423, 'f1': 0.0860997938569367, 'ndcg': 0.08829487146480922}, ('diverse', 'list-size-3', 'a', 'm', '0.9'): {'precision': 0.08561545729402872, 'recall': 0.08620344602487459, 'f1': 0.08585065278636707, 'ndcg': 0.08811949655851391}, ('diverse', 'list-size-3', 'p', 'm', '0.5'): {'precision': 0.06562102315673744, 'recall': 0.0660475073867931, 'f1': 0.0657916168487597, 'ndcg': 0.061235589923007275}, ('diverse', 'list-size-3', 'a', 'm', '0.5'): {'precision': 0.0794669312169312, 'recall': 0.08001241153026867, 'f1': 0.0796851233422662, 'ndcg': 0.08137135226759057}, ('random', 'list-size-3', 'a', 'm', '0.5'): {'precision': 0.10695238095238095, 'recall': 0.10707738095238095, 'f1': 0.10700238095238095, 'ndcg': 0.10925330513757132}, ('random', 'list-size-3', 'a', 'm', '0.7'): {'precision': 0.10936904761904762, 'recall': 0.10949404761904762, 'f1': 0.10941904761904761, 'ndcg': 0.1110158830673583}, ('random', 'list-size-3', 'a', 'm', '0.9'): {'precision': 0.1111190476190476, 'recall': 0.11116071428571428, 'f1': 0.11113571428571427, 'ndcg': 0.11238073961335719}, ('similar', 'list-size-3', 'a', 'm', '0.5'): {'precision': 0.09189727204012918, 'recall': 0.09206563079777363, 'f1': 0.09196461554318697, 'ndcg': 0.09889189154143849}, ('similar', 'list-size-3', 'a', 'm', '0.7'): {'precision': 0.12271529925101352, 'recall': 0.12305201676630247, 'f1': 0.1228499862571291, 'ndcg': 0.12293760483243288}, ('similar', 'list-size-3', 'a', 'm', '0.9'): {'precision': 0.12094916855631141, 'recall': 0.1212017109874253, 'f1': 0.12105018552875695, 'ndcg': 0.12154687431458695}, ('diverse', 'list-size-5', 'a', 'lm', '0.7'): {'precision': 0.07899010513296228, 'recall': 0.08355275974025975, 'f1': 0.08058928489625769, 'ndcg': 0.08533487407139786}, ('diverse', 'list-size-3', 'p', 'm', '0.7'): {'precision': 0.06562102315673744, 'recall': 0.0660475073867931, 'f1': 0.0657916168487597, 'ndcg': 0.061235589923007275}, ('random', 'list-size-3', 'p', 'var', '0.7'): {'precision': 0.08029761904761903, 'recall': 0.08038095238095237, 'f1': 0.08033095238095236, 'ndcg': 0.07976004772057259}, ('diverse', 'list-size-3', 'a', 'j', '0.9'): {'precision': 0.08779493918779632, 'recall': 0.08842458599601456, 'f1': 0.08804679791108362, 'ndcg': 0.08998819528694404}, ('similar', 'list-size-3', 'p', 'var', '0.7'): {'precision': 0.1064645262145262, 'recall': 0.10675746409674983, 'f1': 0.10655670136741566, 'ndcg': 0.10530746590671128}, ('random', 'list-size-3', 'p', 'm', '0.7'): {'precision': 0.0860595238095238, 'recall': 0.08610119047619047, 'f1': 0.08607619047619047, 'ndcg': 0.0836290061445516}, ('diverse', 'list-size-3', 'p', 'var', '0.9'): {'precision': 0.06417551363979936, 'recall': 0.06472912801484229, 'f1': 0.0643714491857349, 'ndcg': 0.06023636451190928}, ('random', 'list-size-5', 'a', 'lm', '0.7'): {'precision': 0.10805714285714285, 'recall': 0.10928630952380951, 'f1': 0.10852142857142859, 'ndcg': 0.11031120354474695}, ('random', 'list-size-3', 'a', 'j', '0.9'): {'precision': 0.11532142857142855, 'recall': 0.11532142857142855, 'f1': 0.11532142857142855, 'ndcg': 0.11556665821622576}, ('similar', 'list-size-3', 'p', 'm', '0.7'): {'precision': 0.11058749055177626, 'recall': 0.11087999896928466, 'f1': 0.11067949391877963, 'ndcg': 0.10857970075963083}, ('random', 'list-size-3', 'p', 'var', '0.9'): {'precision': 0.08547619047619048, 'recall': 0.08551785714285715, 'f1': 0.08549285714285715, 'ndcg': 0.08326446917024756}, ('similar', 'list-size-3', 'a', 'j', '0.9'): {'precision': 0.12136751872466159, 'recall': 0.12162006115577546, 'f1': 0.12146853569710714, 'ndcg': 0.12187208300610512}, ('similar', 'list-size-3', 'p', 'var', '0.9'): {'precision': 0.110889146567718, 'recall': 0.11113956744313887, 'f1': 0.11096431491788634, 'ndcg': 0.10866495896149489}, ('similar', 'list-size-5', 'a', 'lm', '0.7'): {'precision': 0.12162323232323233, 'recall': 0.12369066086030374, 'f1': 0.12232634819199446, 'ndcg': 0.1229509886751784}, ('diverse', 'list-size-5', 'a', 'var', '0.5'): {'precision': 0.07732708719851578, 'recall': 0.0824892427678142, 'f1': 0.07912868218956655, 'ndcg': 0.08401647774759946}, ('random', 'list-size-5', 'a', 'var', '0.5'): {'precision': 0.11132142857142857, 'recall': 0.11288809523809522, 'f1': 0.11186825396825398, 'ndcg': 0.11383650721162838}, ('diverse', 'list-size-3', 'p', 'j', '0.5'): {'precision': 0.061135607778464905, 'recall': 0.06147748745963031, 'f1': 0.061272359650931064, 'ndcg': 0.057824336000631825}, ('similar', 'list-size-5', 'a', 'var', '0.5'): {'precision': 0.12320796742939602, 'recall': 0.12530492166563595, 'f1': 0.12391942963813714, 'ndcg': 0.12416352144787238}, ('diverse', 'list-size-5', 'a', 'var', '0.7'): {'precision': 0.08141406926406926, 'recall': 0.08662238971346116, 'f1': 0.08323384378282339, 'ndcg': 0.08768749749853422}, ('diverse', 'list-size-5', 'a', 'lm', '0.9'): {'precision': 0.07961215213358071, 'recall': 0.08417072424929568, 'f1': 0.08120717925939017, 'ndcg': 0.0857194272920531}, ('random', 'list-size-5', 'a', 'var', '0.7'): {'precision': 0.11232857142857147, 'recall': 0.11376190476190477, 'f1': 0.1128670634920635, 'ndcg': 0.11418228755889107}, ('similar', 'list-size-5', 'a', 'var', '0.7'): {'precision': 0.12285340136054423, 'recall': 0.12497106266749125, 'f1': 0.12357175189700702, 'ndcg': 0.12379643960135975}, ('diverse', 'list-size-5', 'a', 'var', '0.9'): {'precision': 0.08146508967223252, 'recall': 0.08656797395725968, 'f1': 0.08324270392620735, 'ndcg': 0.08769036080354872}, ('random', 'list-size-5', 'a', 'var', '0.9'): {'precision': 0.11232857142857144, 'recall': 0.11371607142857143, 'f1': 0.11284900793650794, 'ndcg': 0.11424152950377404}, ('similar', 'list-size-5', 'a', 'var', '0.9'): {'precision': 0.12260390641104928, 'recall': 0.12468823438466296, 'f1': 0.12330975694751208, 'ndcg': 0.1236376935166407}, ('random', 'list-size-3', 'p', 'j', '0.5'): {'precision': 0.0850595238095238, 'recall': 0.08510119047619047, 'f1': 0.08507619047619046, 'ndcg': 0.08297116996648332}, ('random', 'list-size-5', 'a', 'lm', '0.9'): {'precision': 0.10941428571428573, 'recall': 0.11065595238095238, 'f1': 0.10988412698412701, 'ndcg': 0.11147259958496496}, ('diverse', 'list-size-5', 'p', 'var', '0.5'): {'precision': 0.041883776540919404, 'recall': 0.045328865182436624, 'f1': 0.04308848314698656, 'ndcg': 0.04401473358194787}, ('similar', 'list-size-5', 'a', 'lm', '0.9'): {'precision': 0.12365840032982892, 'recall': 0.12577698756270186, 'f1': 0.12437711562498979, 'ndcg': 0.12421484357749923}, ('diverse', 'list-size-5', 'p', 'lm', '0.5'): {'precision': 0.07162873634302205, 'recall': 0.07544473218580361, 'f1': 0.07296922435400328, 'ndcg': 0.06838209181969411}, ('similar', 'list-size-3', 'p', 'j', '0.5'): {'precision': 0.11055839002267573, 'recall': 0.1108088108980966, 'f1': 0.11063355837284408, 'ndcg': 0.10826255214067834}, ('diverse', 'list-size-3', 'p', 'm', '0.9'): {'precision': 0.06562102315673744, 'recall': 0.0660475073867931, 'f1': 0.0657916168487597, 'ndcg': 0.061235589923007275}, ('random', 'list-size-3', 'p', 'm', '0.9'): {'precision': 0.08614285714285713, 'recall': 0.08618452380952381, 'f1': 0.08615952380952381, 'ndcg': 0.08368766598530444}, ('similar', 'list-size-3', 'p', 'm', '0.9'): {'precision': 0.11031091527520098, 'recall': 0.11060342369270941, 'f1': 0.11040291864220438, 'ndcg': 0.10835398282959388}, ('diverse', 'list-size-5', 'a', 'm', '0.5'): {'precision': 0.07909164089878376, 'recall': 0.08359570964749538, 'f1': 0.0806670973175225, 'ndcg': 0.08535589773138455}, ('diverse', 'list-size-3', 'p', 'j', '0.7'): {'precision': 0.0640801724730296, 'recall': 0.0645921201814059, 'f1': 0.0642594413522985, 'ndcg': 0.06013575278670961}, ('random', 'list-size-5', 'a', 'm', '0.5'): {'precision': 0.0955142857142857, 'recall': 0.09684345238095238, 'f1': 0.09599424603174603, 'ndcg': 0.1014262856671185}, ('similar', 'list-size-5', 'a', 'm', '0.5'): {'precision': 0.07169906204906205, 'recall': 0.07243528482099912, 'f1': 0.07195948699826252, 'ndcg': 0.08347339407820711}, ('random', 'list-size-5', 'p', 'lm', '0.5'): {'precision': 0.09250714285714286, 'recall': 0.0933529761904762, 'f1': 0.09282916666666667, 'ndcg': 0.08917362675193638}, ('random', 'list-size-3', 'p', 'j', '0.7'): {'precision': 0.08547619047619046, 'recall': 0.08551785714285713, 'f1': 0.08549285714285712, 'ndcg': 0.08324910853325893}, ('similar', 'list-size-3', 'p', 'j', '0.7'): {'precision': 0.11080667216381501, 'recall': 0.1110570930392359, 'f1': 0.11088184051398338, 'ndcg': 0.10856051150984063}, ('diverse', 'list-size-5', 'a', 'm', '0.7'): {'precision': 0.07888960008245723, 'recall': 0.0834062950937951, 'f1': 0.0804706681734743, 'ndcg': 0.08524759900443571}, ('random', 'list-size-5', 'a', 'm', '0.7'): {'precision': 0.10396428571428573, 'recall': 0.10556011904761906, 'f1': 0.10450257936507938, 'ndcg': 0.10761377302916522}, ('similar', 'list-size-5', 'a', 'm', '0.7'): {'precision': 0.11771364667078954, 'recall': 0.11929926303854876, 'f1': 0.11827780350475929, 'ndcg': 0.12023066021389842}, ('diverse', 'list-size-5', 'a', 'm', '0.9'): {'precision': 0.07934469181612039, 'recall': 0.08386959389816534, 'f1': 0.08092709267930358, 'ndcg': 0.0855232123456782}, ('similar', 'list-size-5', 'p', 'lm', '0.5'): {'precision': 0.11330971964543395, 'recall': 0.11511430375180376, 'f1': 0.113894980825423, 'ndcg': 0.11193326737836129}, ('random', 'list-size-5', 'a', 'm', '0.9'): {'precision': 0.11021428571428571, 'recall': 0.11177261904761907, 'f1': 0.11075277777777778, 'ndcg': 0.11219588139599801}, ('similar', 'list-size-5', 'a', 'm', '0.9'): {'precision': 0.12296096681096683, 'recall': 0.12518944719301864, 'f1': 0.12371413691498727, 'ndcg': 0.12387429602273774}, ('diverse', 'list-size-5', 'p', 'm', '0.5'): {'precision': 0.07162873634302205, 'recall': 0.07544473218580361, 'f1': 0.07296922435400328, 'ndcg': 0.06838209181969411}, ('diverse', 'list-size-3', 'p', 'j', '0.9'): {'precision': 0.06545445956160242, 'recall': 0.06596640726997868, 'f1': 0.0656337284408713, 'ndcg': 0.061134169917758066}, ('random', 'list-size-5', 'p', 'm', '0.5'): {'precision': 0.09275714285714286, 'recall': 0.0936029761904762, 'f1': 0.09307916666666666, 'ndcg': 0.08933763309882681}, ('similar', 'list-size-5', 'p', 'm', '0.5'): {'precision': 0.11406071943929086, 'recall': 0.11591075551432695, 'f1': 0.11466386667942792, 'ndcg': 0.11241017223922645}, ('random', 'list-size-3', 'p', 'j', '0.9'): {'precision': 0.08647619047619048, 'recall': 0.08651785714285715, 'f1': 0.08649285714285715, 'ndcg': 0.08395302662229306}, ('diverse', 'list-size-5', 'p', 'm', '0.7'): {'precision': 0.07157873634302206, 'recall': 0.07539473218580361, 'f1': 0.07291922435400329, 'ndcg': 0.06834557473223343}, ('random', 'list-size-5', 'p', 'm', '0.7'): {'precision': 0.09320714285714286, 'recall': 0.09400714285714286, 'f1': 0.09351111111111111, 'ndcg': 0.0896080151074302}, ('diverse', 'list-size-5', 'p', 'lm', '0.7'): {'precision': 0.07157873634302206, 'recall': 0.07539473218580361, 'f1': 0.07291922435400329, 'ndcg': 0.06834557473223343}, ('similar', 'list-size-3', 'p', 'j', '0.9'): {'precision': 0.11046825396825395, 'recall': 0.11071867484367484, 'f1': 0.11054342231842232, 'ndcg': 0.10841554591439309}, ('similar', 'list-size-5', 'p', 'm', '0.7'): {'precision': 0.11349067202638632, 'recall': 0.11537236394557823, 'f1': 0.11410557371577781, 'ndcg': 0.11209801442974729}, ('diverse', 'list-size-5', 'p', 'm', '0.9'): {'precision': 0.07162873634302205, 'recall': 0.07544473218580361, 'f1': 0.07296922435400328, 'ndcg': 0.06838209181969411}, ('diverse', 'list-size-5', 'a', 'j', '0.5'): {'precision': 0.05921651205936921, 'recall': 0.06337082130832132, 'f1': 0.06067957249037183, 'ndcg': 0.07053517992112532}, ('diverse', 'list-size-10', 'a', 'lm', '0.5'): {'precision': 0.060989285714285725, 'recall': 0.09272429138321994, 'f1': 0.0704523529234415, 'ndcg': 0.08393339771459934}, ('diverse', 'list-size-10', 'a', 'lm', '0.7'): {'precision': 0.060989285714285725, 'recall': 0.09272429138321994, 'f1': 0.0704523529234415, 'ndcg': 0.08393339771459934}, ('diverse', 'list-size-10', 'a', 'lm', '0.9'): {'precision': 0.060989285714285725, 'recall': 0.09272429138321994, 'f1': 0.0704523529234415, 'ndcg': 0.08393339771459934}, ('diverse', 'list-size-10', 'a', 'var', '0.5'): {'precision': 0.060989285714285725, 'recall': 0.09272429138321994, 'f1': 0.0704523529234415, 'ndcg': 0.08393339771459934}, ('diverse', 'list-size-10', 'a', 'var', '0.7'): {'precision': 0.060989285714285725, 'recall': 0.09272429138321994, 'f1': 0.0704523529234415, 'ndcg': 0.08393339771459934}, ('diverse', 'list-size-10', 'a', 'var', '0.9'): {'precision': 0.060989285714285725, 'recall': 0.09272429138321994, 'f1': 0.0704523529234415, 'ndcg': 0.08393339771459934}, ('similar', 'list-size-10', 'a', 'lm', '0.5'): {'precision': 0.17398928571428574, 'recall': 0.1945575396825397, 'f1': 0.18053181143976427, 'ndcg': 0.18993763523591

## Tables for results

In [29]:

formatted_tables = {}

for (grouping, list_size, utility, method, lam), metrics in results_by_config.items():
    key = (grouping, list_size, utility, method)
    if key not in formatted_tables:
        # Initialize a DataFrame with metrics as index
        formatted_tables[key] = pd.DataFrame(index=['precision', 'recall', 'f1', 'ndcg'])
    for metric_name, value in metrics.items():
        formatted_tables[key].loc[metric_name, lam] = value

# Convert lambda columns to float and sort
for key, df in formatted_tables.items():
    df.columns = df.columns.astype(float)
    formatted_tables[key] = df[sorted(df.columns)]

In [30]:
from IPython.display import display

for key, df in formatted_tables.items():
    print(f"\nResults for {key}:")
    display(df)

Results for ('diverse', 'list-size-3', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.085699  0.085865  0.085615
recall     0.086287  0.086453  0.086203
f1         0.085934  0.086100  0.085851
ndcg       0.088178  0.088295  0.088119

Results for ('random', 'list-size-3', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.109036  0.109369  0.111036
recall     0.109077  0.109411  0.111077
f1         0.109052  0.109386  0.111052
ndcg       0.110745  0.110980  0.112307

Results for ('diverse', 'list-size-3', 'a', 'j'):

                0.5       0.7       0.9
precision  0.076598  0.085353  0.087795
recall     0.077144  0.085898  0.088425
f1         0.076817  0.085571  0.088047
ndcg       0.081729  0.088047  0.089988

Results for ('similar', 'list-size-3', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.121957  0.122126  0.120695
recall     0.122251  0.122421  0.120947
f1         0.122075  0.122244  0.120796
ndcg       0.122273  0.122377  0.121352

Results for ('random', 'list-size-3', 'a', 'j'):

                0.5       0.7       0.9
precision  0.108393  0.115405  0.115321
recall     0.108435  0.115488  0.115321
f1         0.108410  0.115438  0.115321
ndcg       0.110480  0.115989  0.115567

Results for ('similar', 'list-size-3', 'a', 'j'):

                0.5       0.7       0.9
precision  0.123978  0.121785  0.121368
recall     0.124230  0.122038  0.121620
f1         0.124079  0.121886  0.121469
ndcg       0.123725  0.122197  0.121872

Results for ('random', 'list-size-3', 'p', 'var'):

                0.5       0.7       0.9
precision  0.065131  0.080298  0.085476
recall     0.065173  0.080381  0.085518
f1         0.065148  0.080331  0.085493
ndcg       0.067232  0.079760  0.083264

Results for ('random', 'list-size-3', 'p', 'm'):

                0.5       0.7       0.9
precision  0.086143  0.086060  0.086143
recall     0.086185  0.086101  0.086185
f1         0.086160  0.086076  0.086160
ndcg       0.083688  0.083629  0.083688

Results for ('similar', 'list-size-3', 'p', 'var'):

                0.5       0.7       0.9
precision  0.085658  0.106465  0.110889
recall     0.085951  0.106757  0.111140
f1         0.085750  0.106557  0.110964
ndcg       0.088233  0.105307  0.108665

Results for ('similar', 'list-size-3', 'p', 'm'):

                0.5       0.7       0.9
precision  0.110503  0.110587  0.110311
recall     0.110796  0.110880  0.110603
f1         0.110595  0.110679  0.110403
ndcg       0.108443  0.108580  0.108354

Results for ('diverse', 'list-size-3', 'p', 'var'):

                0.5       0.7       0.9
precision  0.040952  0.057262  0.064176
recall     0.041414  0.057562  0.064729
f1         0.041136  0.057382  0.064371
ndcg       0.042137  0.054722  0.060236

Results for ('diverse', 'list-size-3', 'p', 'lm'):

                0.5       0.7       0.9
precision  0.065621  0.065621  0.065621
recall     0.066048  0.066048  0.066048
f1         0.065792  0.065792  0.065792
ndcg       0.061236  0.061236  0.061236

Results for ('random', 'list-size-3', 'p', 'lm'):

                0.5       0.7       0.9
precision  0.086143  0.086060  0.086143
recall     0.086185  0.086101  0.086185
f1         0.086160  0.086076  0.086160
ndcg       0.083688  0.083629  0.083688

Results for ('similar', 'list-size-3', 'p', 'lm'):

                0.5       0.7       0.9
precision  0.110588  0.110587  0.110503
recall     0.110880  0.110880  0.110796
f1         0.110680  0.110679  0.110595
ndcg       0.108518  0.108580  0.108489

Results for ('diverse', 'list-size-5', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.079192  0.078990  0.079612
recall     0.083730  0.083553  0.084171
f1         0.080780  0.080589  0.081207
ndcg       0.085438  0.085335  0.085719

Results for ('random', 'list-size-5', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.107257  0.108057  0.109414
recall     0.108486  0.109286  0.110656
f1         0.107721  0.108521  0.109884
ndcg       0.109741  0.110311  0.111473

Results for ('similar', 'list-size-5', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.122075  0.121623  0.123658
recall     0.124269  0.123691  0.125777
f1         0.122827  0.122326  0.124377
ndcg       0.123312  0.122951  0.124215

Results for ('random', 'list-size-3', 'a', 'var'):

                0.5       0.7       0.9
precision  0.116155  0.113738  0.114905
recall     0.116196  0.113738  0.114905
f1         0.116171  0.113738  0.114905
ndcg       0.116330  0.114483  0.115273

Results for ('diverse', 'list-size-3', 'a', 'var'):

                0.5       0.7       0.9
precision  0.079270  0.088046  0.087962
recall     0.080067  0.088675  0.088591
f1         0.079564  0.088298  0.088213
ndcg       0.081404  0.090149  0.090106

Results for ('similar', 'list-size-3', 'a', 'var'):

                0.5       0.7       0.9
precision  0.122631  0.121281  0.121368
recall     0.122884  0.121533  0.121621
f1         0.122732  0.121382  0.121469
ndcg       0.122844  0.121811  0.121873

Results for ('diverse', 'list-size-3', 'a', 'm'):

                0.5       0.7       0.9
precision  0.079467  0.085865  0.085615
recall     0.080012  0.086453  0.086203
f1         0.079685  0.086100  0.085851
ndcg       0.081371  0.088295  0.088119

Results for ('diverse', 'list-size-3', 'p', 'm'):

                0.5       0.7       0.9
precision  0.065621  0.065621  0.065621
recall     0.066048  0.066048  0.066048
f1         0.065792  0.065792  0.065792
ndcg       0.061236  0.061236  0.061236

Results for ('random', 'list-size-3', 'a', 'm'):

                0.5       0.7       0.9
precision  0.106952  0.109369  0.111119
recall     0.107077  0.109494  0.111161
f1         0.107002  0.109419  0.111136
ndcg       0.109253  0.111016  0.112381

Results for ('similar', 'list-size-3', 'a', 'm'):

                0.5       0.7       0.9
precision  0.091897  0.122715  0.120949
recall     0.092066  0.123052  0.121202
f1         0.091965  0.122850  0.121050
ndcg       0.098892  0.122938  0.121547

Results for ('diverse', 'list-size-5', 'a', 'var'):

                0.5       0.7       0.9
precision  0.077327  0.081414  0.081465
recall     0.082489  0.086622  0.086568
f1         0.079129  0.083234  0.083243
ndcg       0.084016  0.087687  0.087690

Results for ('random', 'list-size-5', 'a', 'var'):

                0.5       0.7       0.9
precision  0.111321  0.112329  0.112329
recall     0.112888  0.113762  0.113716
f1         0.111868  0.112867  0.112849
ndcg       0.113837  0.114182  0.114242

Results for ('diverse', 'list-size-3', 'p', 'j'):

                0.5       0.7       0.9
precision  0.061136  0.064080  0.065454
recall     0.061477  0.064592  0.065966
f1         0.061272  0.064259  0.065634
ndcg       0.057824  0.060136  0.061134

Results for ('similar', 'list-size-5', 'a', 'var'):

                0.5       0.7       0.9
precision  0.123208  0.122853  0.122604
recall     0.125305  0.124971  0.124688
f1         0.123919  0.123572  0.123310
ndcg       0.124164  0.123796  0.123638

Results for ('random', 'list-size-3', 'p', 'j'):

                0.5       0.7       0.9
precision  0.085060  0.085476  0.086476
recall     0.085101  0.085518  0.086518
f1         0.085076  0.085493  0.086493
ndcg       0.082971  0.083249  0.083953

Results for ('diverse', 'list-size-5', 'p', 'var'):

                0.5
precision  0.041884
recall     0.045329
f1         0.043088
ndcg       0.044015

Results for ('diverse', 'list-size-5', 'p', 'lm'):

                0.5       0.7
precision  0.071629  0.071579
recall     0.075445  0.075395
f1         0.072969  0.072919
ndcg       0.068382  0.068346

Results for ('similar', 'list-size-3', 'p', 'j'):

                0.5       0.7       0.9
precision  0.110558  0.110807  0.110468
recall     0.110809  0.111057  0.110719
f1         0.110634  0.110882  0.110543
ndcg       0.108263  0.108561  0.108416

Results for ('diverse', 'list-size-5', 'a', 'm'):

                0.5       0.7       0.9
precision  0.079092  0.078890  0.079345
recall     0.083596  0.083406  0.083870
f1         0.080667  0.080471  0.080927
ndcg       0.085356  0.085248  0.085523

Results for ('random', 'list-size-5', 'a', 'm'):

                0.5       0.7       0.9
precision  0.095514  0.103964  0.110214
recall     0.096843  0.105560  0.111773
f1         0.095994  0.104503  0.110753
ndcg       0.101426  0.107614  0.112196

Results for ('similar', 'list-size-5', 'a', 'm'):

                0.5       0.7       0.9
precision  0.071699  0.117714  0.122961
recall     0.072435  0.119299  0.125189
f1         0.071959  0.118278  0.123714
ndcg       0.083473  0.120231  0.123874

Results for ('random', 'list-size-5', 'p', 'lm'):

                0.5
precision  0.092507
recall     0.093353
f1         0.092829
ndcg       0.089174

Results for ('similar', 'list-size-5', 'p', 'lm'):

                0.5
precision  0.113310
recall     0.115114
f1         0.113895
ndcg       0.111933

Results for ('diverse', 'list-size-5', 'p', 'm'):

                0.5       0.7       0.9
precision  0.071629  0.071579  0.071629
recall     0.075445  0.075395  0.075445
f1         0.072969  0.072919  0.072969
ndcg       0.068382  0.068346  0.068382

Results for ('random', 'list-size-5', 'p', 'm'):

                0.5       0.7
precision  0.092757  0.093207
recall     0.093603  0.094007
f1         0.093079  0.093511
ndcg       0.089338  0.089608

Results for ('similar', 'list-size-5', 'p', 'm'):

                0.5       0.7
precision  0.114061  0.113491
recall     0.115911  0.115372
f1         0.114664  0.114106
ndcg       0.112410  0.112098

Results for ('diverse', 'list-size-5', 'a', 'j'):

                0.5
precision  0.059217
recall     0.063371
f1         0.060680
ndcg       0.070535

Results for ('diverse', 'list-size-10', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.060989  0.060989  0.060989
recall     0.092724  0.092724  0.092724
f1         0.070452  0.070452  0.070452
ndcg       0.083933  0.083933  0.083933

Results for ('diverse', 'list-size-10', 'a', 'var'):

                0.5       0.7       0.9
precision  0.060989  0.060989  0.060989
recall     0.092724  0.092724  0.092724
f1         0.070452  0.070452  0.070452
ndcg       0.083933  0.083933  0.083933

Results for ('similar', 'list-size-10', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.173989  0.173989  0.173989
recall     0.194558  0.194558  0.194558
f1         0.180532  0.180532  0.180532
ndcg       0.189938  0.189938  0.189938

Results for ('similar', 'list-size-10', 'a', 'var'):

                0.5       0.7       0.9
precision  0.173989  0.173989  0.173989
recall     0.194558  0.194558  0.194558
f1         0.180532  0.180532  0.180532
ndcg       0.189938  0.189938  0.189938

Results for ('random', 'list-size-10', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.106621  0.106621  0.106621
recall     0.120252  0.120252  0.120252
f1         0.110821  0.110821  0.110821
ndcg       0.120335  0.120335  0.120335

Results for ('random', 'list-size-10', 'a', 'var'):

                0.5       0.7       0.9
precision  0.106621  0.106621  0.106621
recall     0.120252  0.120252  0.120252
f1         0.110821  0.110821  0.110821
ndcg       0.120335  0.120335  0.120335

In [31]:
output_dir = "/content/formatted_binary_tables_csv"
os.makedirs(output_dir, exist_ok=True)

for key, df in formatted_tables.items():
    grouping, list_size, utility, method = key

    filename = f"{grouping}_list-size-{list_size}_{utility}_{method}.csv"
    filepath = os.path.join(output_dir, filename)

    df.to_csv(filepath)

    print(f"Saved: {filepath}")

Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-3_a_lm.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-3_a_lm.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-3_a_j.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-3_a_lm.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-3_a_j.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-3_a_j.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-3_p_var.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-3_p_m.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-3_p_var.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-3_p_m.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-3_p_var.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-3_p_lm.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-3_p_lm.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-3_p_lm.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-5_a_lm.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-5_a_lm.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-5_a_lm.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-3_a_var.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-3_a_var.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-3_a_var.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-3_a_m.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-3_p_m.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-3_a_m.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-3_a_m.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-5_a_var.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-5_a_var.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-3_p_j.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-5_a_var.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-3_p_j.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-5_p_var.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-5_p_lm.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-3_p_j.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-5_a_m.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-5_a_m.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-5_a_m.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-5_p_lm.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-5_p_lm.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-5_p_m.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-5_p_m.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-5_p_m.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-5_a_j.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-10_a_lm.csv
Saved: /content/formatted_binary_tables_csv/diverse_list-size-list-size-10_a_var.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-10_a_lm.csv
Saved: /content/formatted_binary_tables_csv/similar_list-size-list-size-10_a_var.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-10_a_lm.csv
Saved: /content/formatted_binary_tables_csv/random_list-size-list-size-10_a_var.csv

# Borda Relevance

## borda eval

In [35]:
import numpy as np
import math
import pandas as pd

def evaluate_borda(group, recommendations, test_matrix, k=10):
    precision_scores = []
    recall_scores = []
    f_scores = []
    ndcg_scores = []

    for user in group:
        if user not in test_matrix.index:
            continue

        user_row = test_matrix.loc[user].dropna()
        if user_row.empty:
            continue

        items = user_row.index.to_numpy()
        ratings = user_row.to_numpy()

        sort_indices = np.argsort(-ratings)
        sorted_items = items[sort_indices]
        sorted_scores = np.arange(len(items), 0, -1)  # Borda scores: n, n-1, ..., 1

        borda_scores = dict(zip(sorted_items, sorted_scores))

        recommended_items = recommendations[:k]
        hits = np.array([borda_scores.get(item, 0) for item in recommended_items])

        max_possible = sorted_scores[:min(k, len(sorted_scores))].sum()

        max_borda = sorted_scores[0] if sorted_scores.size > 0 else 1
        precision = hits.sum() / (k * max_borda)
        recall = hits.sum() / max_possible if max_possible > 0 else 0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

        discounts = np.log2(np.arange(2, 2 + len(hits)))
        dcg = (hits / discounts).sum()
        ideal_hits = sorted_scores[:len(hits)]
        idcg = (ideal_hits / discounts[:len(ideal_hits)]).sum()
        ndcg = dcg / idcg if idcg > 0 else 0

        precision_scores.append(precision)
        recall_scores.append(recall)
        f_scores.append(f1)
        ndcg_scores.append(ndcg)

    return {
        'precision': float(np.mean(precision_scores)),
        'recall': float(np.mean(recall_scores)),
        'f1': float(np.mean(f_scores)),
        'ndcg': float(np.mean(ndcg_scores))
    }

## Eval single fold (borda)

In [38]:
def borda_evaluate_indiv_fold(group_data, test_matrix, k):
  fold_precesion_scores = []
  fold_recall_scores = []
  fold_f_scores = []
  fold_ndcg_scores = []

  for key, items in group_data.items():
    group = [int(x) for x in key.split(',')]
    recs = [str(x) for x in items]
    metrics = evaluate_borda(group, recs, test_matrix, k)

    fold_precesion_scores.append(metrics['precision'])
    fold_recall_scores.append(metrics['recall'])
    fold_f_scores.append(metrics['f1'])
    fold_ndcg_scores.append(metrics['ndcg'])

  return {
      'precision': float(np.mean(fold_precesion_scores)),
      'recall': float(np.mean(fold_recall_scores)),
      'f1': float(np.mean(fold_f_scores)),
      'ndcg': float(np.mean(fold_ndcg_scores))
  }

## Main Driver (Borda)

In [39]:
borda_results_by_config = {}

for group in final_groups:
  fold_metrics = []

  # need to find k group was evaluated using
  file = group[0]
  parts = file.split('_')
  val = parts[5]
  k = int(val.split('-')[2])
  # print(k)x
  for fold_idx, filename in enumerate(group):
    # need to find k val

    file_path = os.path.join(output_folder, filename)
    with open(file_path, 'r') as json_file:
        group_data = json.load(json_file)

    test_matrix = test_matrices[fold_idx]
    metrics = borda_evaluate_indiv_fold(group_data, test_matrix, k)
    fold_metrics.append(metrics)


    avg_metrics = {
    'precision': float(np.mean([m['precision'] for m in fold_metrics])),
    'recall': float(np.mean([m['recall'] for m in fold_metrics])),
    'f1': float(np.mean([m['f1'] for m in fold_metrics])),
    'ndcg': float(np.mean([m['ndcg'] for m in fold_metrics]))
    }

    parts = group[0].split('_')
    group_type = parts[0]
    list_size = parts[5]            # e.g., 'list-size-3'
    utility = parts[6]              # e.g., 'a'
    fairness = parts[7]            # e.g., 'var'
    lambda_val = parts[8]          # e.g., '0.5'

    config_key = (group_type, list_size, utility, fairness, lambda_val)
    borda_results_by_config[config_key] = avg_metrics

### Tables for results

In [40]:
formatted_tables = {}

for (grouping, list_size, utility, method, lam), metrics in borda_results_by_config.items():
    key = (grouping, list_size, utility, method)
    if key not in formatted_tables:
        formatted_tables[key] = pd.DataFrame(index=['precision', 'recall', 'f1', 'ndcg'])
    for metric_name, value in metrics.items():
        formatted_tables[key].loc[metric_name, lam] = value

for key, df in formatted_tables.items():
    df.columns = df.columns.astype(float)
    formatted_tables[key] = df[sorted(df.columns)]

In [41]:
from IPython.display import display

for key, df in formatted_tables.items():
    print(f"\nResults for {key}:")
    display(df)

Results for ('diverse', 'list-size-3', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.072208  0.072311  0.072167
recall     0.083394  0.083496  0.083353
f1         0.077119  0.077222  0.077078
ndcg       0.082923  0.082995  0.082894

Results for ('random', 'list-size-3', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.089423  0.089573  0.091268
recall     0.095104  0.095243  0.096963
f1         0.092059  0.092204  0.093909
ndcg       0.096261  0.096361  0.097681

Results for ('diverse', 'list-size-3', 'a', 'j'):

                0.5       0.7       0.9
precision  0.064923  0.071676  0.073516
recall     0.075453  0.082885  0.085107
f1         0.069531  0.076605  0.078601
ndcg       0.077393  0.082605  0.084240

Results for ('similar', 'list-size-3', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.104225  0.104421  0.103916
recall     0.109960  0.110158  0.109608
f1         0.106826  0.107024  0.106503
ndcg       0.110246  0.110388  0.110058

Results for ('random', 'list-size-3', 'a', 'j'):

                0.5       0.7       0.9
precision  0.085635  0.092247  0.092850
recall     0.091601  0.098375  0.098695
f1         0.088386  0.095074  0.095566
ndcg       0.093504  0.098781  0.098814

Results for ('similar', 'list-size-3', 'a', 'j'):

                0.5       0.7       0.9
precision  0.106143  0.104912  0.104472
recall     0.112050  0.110814  0.110362
f1         0.108827  0.107589  0.107143
ndcg       0.111779  0.110917  0.110584

Results for ('random', 'list-size-3', 'p', 'var'):

                0.5       0.7       0.9
precision  0.054444  0.063851  0.067064
recall     0.057996  0.067805  0.071129
f1         0.056083  0.065671  0.068948
ndcg       0.058441  0.066392  0.068664

Results for ('random', 'list-size-3', 'p', 'm'):

                0.5       0.7       0.9
precision  0.067554  0.067523  0.067554
recall     0.071666  0.071583  0.071666
f1         0.069459  0.069407  0.069459
ndcg       0.069025  0.068978  0.069025

Results for ('similar', 'list-size-3', 'p', 'var'):

                0.5       0.7       0.9
precision  0.067195  0.084370  0.090258
recall     0.071886  0.089467  0.095468
f1         0.069302  0.086673  0.092627
ndcg       0.073667  0.087911  0.092637

Results for ('similar', 'list-size-3', 'p', 'm'):

                0.5       0.7       0.9
precision  0.090459  0.090616  0.090528
recall     0.095783  0.095951  0.095848
f1         0.092869  0.093032  0.092937
ndcg       0.092954  0.093122  0.093022

Results for ('diverse', 'list-size-3', 'p', 'var'):

                0.5       0.7       0.9
precision  0.037627  0.047850  0.054183
recall     0.044136  0.055377  0.062801
f1         0.040446  0.051172  0.057945
ndcg       0.042960  0.051399  0.057026

Results for ('diverse', 'list-size-3', 'p', 'lm'):

                0.5       0.7       0.9
precision  0.055256  0.055256  0.055256
recall     0.063651  0.063651  0.063651
f1         0.058951  0.058951  0.058951
ndcg       0.057684  0.057684  0.057684

Results for ('random', 'list-size-3', 'p', 'lm'):

                0.5       0.7       0.9
precision  0.067554  0.067523  0.067554
recall     0.071666  0.071583  0.071666
f1         0.069459  0.069407  0.069459
ndcg       0.069025  0.068978  0.069025

Results for ('similar', 'list-size-3', 'p', 'lm'):

                0.5       0.7       0.9
precision  0.090604  0.090579  0.090603
recall     0.095903  0.095901  0.095926
f1         0.093005  0.092988  0.093013
ndcg       0.093063  0.093089  0.093076

Results for ('diverse', 'list-size-5', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.065154  0.065049  0.065271
recall     0.090136  0.089986  0.090283
f1         0.074433  0.074305  0.074559
ndcg       0.086482  0.086401  0.086563

Results for ('random', 'list-size-5', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.085516  0.086104  0.087142
recall     0.098458  0.099160  0.100029
f1         0.090860  0.091499  0.092466
ndcg       0.097791  0.098256  0.099085

Results for ('similar', 'list-size-5', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.101454  0.100993  0.102970
recall     0.115276  0.114563  0.116862
f1         0.106945  0.106403  0.108520
ndcg       0.112919  0.112528  0.114006

Results for ('random', 'list-size-3', 'a', 'var'):

                0.5       0.7       0.9
precision  0.092942  0.091751  0.092613
recall     0.099124  0.097501  0.098428
f1         0.095800  0.094422  0.095315
ndcg       0.099129  0.098006  0.098632

Results for ('diverse', 'list-size-3', 'a', 'var'):

                0.5       0.7       0.9
precision  0.067241  0.073820  0.073651
recall     0.078613  0.085463  0.085308
f1         0.072176  0.078927  0.078763
ndcg       0.077541  0.084474  0.084367

Results for ('similar', 'list-size-3', 'a', 'var'):

                0.5       0.7       0.9
precision  0.105106  0.104488  0.104360
recall     0.111029  0.110377  0.110249
f1         0.107793  0.107159  0.107030
ndcg       0.111101  0.110595  0.110505

Results for ('diverse', 'list-size-3', 'a', 'm'):

                0.5       0.7       0.9
precision  0.067506  0.072311  0.072167
recall     0.078363  0.083496  0.083353
f1         0.072270  0.077222  0.077078
ndcg       0.077472  0.082995  0.082894

Results for ('diverse', 'list-size-3', 'p', 'm'):

                0.5       0.7       0.9
precision  0.055256  0.055256  0.055256
recall     0.063651  0.063651  0.063651
f1         0.058951  0.058951  0.058951
ndcg       0.057684  0.057684  0.057684

Results for ('random', 'list-size-3', 'a', 'm'):

                0.5       0.7       0.9
precision  0.086916  0.089102  0.090960
recall     0.092617  0.094870  0.096658
f1         0.089542  0.091761  0.093603
ndcg       0.094395  0.096042  0.097482

Results for ('similar', 'list-size-3', 'a', 'm'):

                0.5       0.7       0.9
precision  0.072221  0.103780  0.104071
recall     0.076017  0.109440  0.109785
f1         0.073960  0.106345  0.106668
ndcg       0.083714  0.109861  0.110194

Results for ('diverse', 'list-size-5', 'a', 'var'):

                0.5       0.7       0.9
precision  0.063088  0.066235  0.066359
recall     0.089287  0.093432  0.093398
f1         0.072669  0.076218  0.076309
ndcg       0.085131  0.088519  0.088548

Results for ('random', 'list-size-5', 'a', 'var'):

                0.5       0.7       0.9
precision  0.086432  0.088028  0.087964
recall     0.100346  0.101630  0.101419
f1         0.092085  0.093600  0.093488
ndcg       0.099386  0.100118  0.100091

Results for ('diverse', 'list-size-3', 'p', 'j'):

                0.5       0.7       0.9
precision  0.052039  0.054052  0.055182
recall     0.060212  0.062585  0.063798
f1         0.055639  0.057785  0.058955
ndcg       0.055155  0.056875  0.057741

Results for ('similar', 'list-size-5', 'a', 'var'):

                0.5       0.7       0.9
precision  0.102419  0.102204  0.102007
recall     0.116166  0.115979  0.115714
f1         0.107912  0.107702  0.107483
ndcg       0.113740  0.113538  0.113378

Results for ('random', 'list-size-3', 'p', 'j'):

                0.5       0.7       0.9
precision  0.067192  0.067022  0.067819
recall     0.071266  0.071107  0.071952
f1         0.069082  0.068915  0.069735
ndcg       0.068801  0.068643  0.069245

Results for ('diverse', 'list-size-5', 'p', 'var'):

                0.5
precision  0.036933
recall     0.053992
f1         0.043063
ndcg       0.048368

Results for ('diverse', 'list-size-5', 'p', 'lm'):

                0.5       0.7
precision  0.056422  0.056413
recall     0.078369  0.078351
f1         0.064595  0.064583
ndcg       0.067204  0.067194

Results for ('similar', 'list-size-3', 'p', 'j'):

                0.5       0.7       0.9
precision  0.089297  0.090224  0.090132
recall     0.094456  0.095431  0.095373
f1         0.091641  0.092591  0.092514
ndcg       0.091746  0.092586  0.092620

Results for ('diverse', 'list-size-5', 'a', 'm'):

                0.5       0.7       0.9
precision  0.065065  0.064964  0.065147
recall     0.089952  0.089803  0.090050
f1         0.074315  0.074191  0.074400
ndcg       0.086383  0.086303  0.086433

Results for ('random', 'list-size-5', 'a', 'm'):

                0.5       0.7       0.9
precision  0.075346  0.081564  0.087539
recall     0.087761  0.094756  0.101173
f1         0.080409  0.086911  0.093090
ndcg       0.090152  0.095051  0.099678

Results for ('similar', 'list-size-5', 'a', 'm'):

                0.5       0.7       0.9
precision  0.055990  0.096826  0.102516
recall     0.062577  0.109006  0.116493
f1         0.058678  0.101759  0.108072
ndcg       0.072580  0.108939  0.113794

Results for ('random', 'list-size-5', 'p', 'lm'):

                0.5
precision  0.071242
recall     0.081461
f1         0.075488
ndcg       0.075760

Results for ('similar', 'list-size-5', 'p', 'lm'):

                0.5
precision  0.088846
recall     0.101594
f1         0.093903
ndcg       0.096933

Results for ('diverse', 'list-size-5', 'p', 'm'):

                0.5       0.7       0.9
precision  0.056422  0.056413  0.056420
recall     0.078369  0.078351  0.078368
f1         0.064595  0.064583  0.064593
ndcg       0.067204  0.067194  0.067203

Results for ('random', 'list-size-5', 'p', 'm'):

                0.5       0.7
precision  0.071372  0.071669
recall     0.081612  0.081833
f1         0.075627  0.075907
ndcg       0.075855  0.076013

Results for ('similar', 'list-size-5', 'p', 'm'):

                0.5       0.7
precision  0.089441  0.089109
recall     0.102307  0.101930
f1         0.094544  0.094189
ndcg       0.097343  0.097162

Results for ('diverse', 'list-size-5', 'a', 'j'):

                0.5
precision  0.050110
recall     0.071948
f1         0.058068
ndcg       0.073627

Results for ('diverse', 'list-size-10', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.043583  0.043583  0.043583
recall     0.107241  0.107241  0.107241
f1         0.059473  0.059473  0.059473
ndcg       0.085129  0.085129  0.085129

Results for ('diverse', 'list-size-10', 'a', 'var'):

                0.5       0.7       0.9
precision  0.043583  0.043583  0.043583
recall     0.107241  0.107241  0.107241
f1         0.059473  0.059473  0.059473
ndcg       0.085129  0.085129  0.085129

Results for ('similar', 'list-size-10', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.131992  0.131992  0.131992
recall     0.192619  0.192619  0.192619
f1         0.150409  0.150409  0.150409
ndcg       0.175734  0.175734  0.175734

Results for ('similar', 'list-size-10', 'a', 'var'):

                0.5       0.7       0.9
precision  0.131992  0.131992  0.131992
recall     0.192619  0.192619  0.192619
f1         0.150409  0.150409  0.150409
ndcg       0.175734  0.175734  0.175734

Results for ('random', 'list-size-10', 'a', 'lm'):

                0.5       0.7       0.9
precision  0.076969  0.076969  0.076969
recall     0.117779  0.117779  0.117779
f1         0.089322  0.089322  0.089322
ndcg       0.108126  0.108126  0.108126

Results for ('random', 'list-size-10', 'a', 'var'):

                0.5       0.7       0.9
precision  0.076969  0.076969  0.076969
recall     0.117779  0.117779  0.117779
f1         0.089322  0.089322  0.089322
ndcg       0.108126  0.108126  0.108126

In [42]:
output_dir = "/content/formatted_borda_tables_csv"
os.makedirs(output_dir, exist_ok=True)

for key, df in formatted_tables.items():
    grouping, list_size, utility, method = key

    filename = f"{grouping}_list-size-{list_size}_{utility}_{method}.csv"
    filepath = os.path.join(output_dir, filename)

    df.to_csv(filepath)

    print(f"Saved: {filepath}")

Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-3_a_lm.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-3_a_lm.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-3_a_j.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-3_a_lm.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-3_a_j.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-3_a_j.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-3_p_var.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-3_p_m.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-3_p_var.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-3_p_m.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-3_p_var.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-3_p_lm.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-3_p_lm.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-3_p_lm.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-5_a_lm.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-5_a_lm.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-5_a_lm.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-3_a_var.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-3_a_var.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-3_a_var.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-3_a_m.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-3_p_m.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-3_a_m.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-3_a_m.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-5_a_var.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-5_a_var.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-3_p_j.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-5_a_var.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-3_p_j.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-5_p_var.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-5_p_lm.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-3_p_j.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-5_a_m.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-5_a_m.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-5_a_m.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-5_p_lm.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-5_p_lm.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-5_p_m.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-5_p_m.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-5_p_m.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-5_a_j.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-10_a_lm.csv
Saved: /content/formatted_borda_tables_csv/diverse_list-size-list-size-10_a_var.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-10_a_lm.csv
Saved: /content/formatted_borda_tables_csv/similar_list-size-list-size-10_a_var.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-10_a_lm.csv
Saved: /content/formatted_borda_tables_csv/random_list-size-list-size-10_a_var.csv

In [45]:
import shutil
from google.colab import files


shutil.make_archive("formatted_binary_tables", "zip", "/content/formatted_binary_tables_csv")
shutil.make_archive("formatted_borda_tables", "zip", "/content/formatted_borda_tables_csv")


# files.download("formatted_binary_tables.zip")
files.download("formatted_borda_tables.zip")